Repository google-terraform-modules/terraform-google-kubernetes-engine, pull requests merged in 2018-10, with the labels that each got.

#20 Extra parameters to node_config
  main.tf
Labels: enhancement

#22 Delete beta parameters
  CHANGELOG.md
  README.md
  main.tf
  outputs.tf
  variables.tf
Labels: documentation, enhancement

#23 Fixing README
  CHANGELOG.md
  README.md
Labels: documentation
